# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# Custom build to run automated tests with Cypress

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'



  stages:
  # Default stage (to run tests in Electron environment)
  - template: templates/stages/defaultStage.yml
    parameters:
      imageName: 'ubuntu-latest'

  - template: templates/stages/chromeStage.yml
    parameters:
      imageName: 'ubuntu-latest'

  - template: templates/stages/firefoxStage.yml
    parameters:
      imageName: 'ubuntu-latest'

  - template: templates/stages/edgeStage.yml
    parameters:
      imageName: 'windows-latest'

- script: |
    npm install
    npm run build
    displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'CypressTestResult'
        publishLocation: 'Container'


